# Generated by Django 5.2.4 on 2025-07-29 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_technology_project_live_demo_alter_project_github_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='challenge',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='role',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='solution',
            field=models.TextField(blank=True, null=True),
        ),
    ]
