# Generated by Django 5.2.4 on 2025-07-29 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_project_challenge_project_role_project_solution'),
    ]

    operations = [
        migrations.AddField(
            model_name='technology',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='tech_icons/'),
        ),
    ]
