# Generated by Django 5.2.4 on 2025-09-23 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_project_image_alter_projectimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='image',
            field=models.URLField(blank=True, help_text='Paste a Cloudinary image URL here', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.URLField(blank=True, help_text='Paste a Cloudinary image URL here', null=True),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='image',
            field=models.URLField(blank=True, help_text='Paste a Cloudinary image URL here', null=True),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='image',
            field=models.URLField(blank=True, help_text='Paste a Cloudinary image URL here', null=True),
        ),
    ]
