services:
  - type: web
    name: portfolio
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python portfolio/manage.py collectstatic --noinput
    startCommand: gunicorn portfolio.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.12
      - key: DJANGO_SETTINGS_MODULE
        value: portfolio.settings
